-- ═══════════════════════════════════════════════════════════════
--  incremental_conducta.sql
--
--  REAC 2026 grades conducta as a mark in its own right, with the same
--  70 floor as an academic subject in secondary; below it a student is
--  aplazado por conducta. `discipline_records` was written to by
--  teachers and never scored, so the app could not produce a mark the
--  regulation requires.
--
--  Every student starts a period at 100 and a teacher deducts points on
--  each record. There is deliberately no severity-to-points scale and no
--  school-wide weighting: the points a teacher enters ARE the deduction,
--  so every point of a conducta grade traces back to one named record.
--  `severity` stays for the register and carries no weight, as do
--  `resolved` and `resolution`, which survive here but no longer surface
--  in the UI.
--
--  conduct_points defaults to 0, which is exactly today's behaviour —
--  every existing record deducts nothing and no student's conducta moves
--  until a teacher enters points on one.
--
--  The pair mirrors the academic grade path exactly: a computed view
--  (student_period_conduct, the live number) beside a posted table
--  (student_conduct_grades, the frozen report-card number), the same
--  shape as student_period_grades beside student_grades. Posting is what
--  stops a late-filed deduction moving a published grade.
--
--  Already inlined in school_schema.sql for fresh per-school projects.
--  Apply this snippet by hand to a project that predates it — see
--  docs/ONBOARDING_RUNBOOK.md. Idempotent: safe to re-run.
--
--  Adds a NEW TABLE, so demo_lockdown.sql MUST be re-run on the demo
--  project afterwards. rls_audit.sql after that.
-- ═══════════════════════════════════════════════════════════════

-- ── The deduction, on the record that justifies it ─────────────
alter table public.discipline_records
  add column if not exists conduct_points numeric(5,2) not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'discipline_records_conduct_points_check'
  ) then
    alter table public.discipline_records
      add constraint discipline_records_conduct_points_check
      check (conduct_points >= 0 and conduct_points <= 100);
  end if;
end $$;

-- ── student_conduct_grades ─────────────────────────────────────
-- The posted conducta: one institutional mark per student per period,
-- with no subject dimension, because the MEP report card carries one
-- conducta and not one per subject. Posting freezes the period — the
-- computed view keeps moving as records are filed, this does not.
create table if not exists public.student_conduct_grades (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  grading_period_id integer not null references public.grading_periods(id) on delete cascade,
  score numeric(5,2) check (score >= 0 and score <= 100),
  notes text,
  submitted_at timestamp with time zone default now(),
  unique (student_id, grading_period_id)
);

create index if not exists idx_student_conduct_grades_period
  on public.student_conduct_grades(grading_period_id);

alter table public.student_conduct_grades enable row level security;

drop policy if exists "Admins have full access to student_conduct_grades" on public.student_conduct_grades;
create policy "Admins have full access to student_conduct_grades" on public.student_conduct_grades
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Any teacher of the student may post. Deliberately NOT narrowed to one
-- teacher the way the discipline write policies are: conducta is a single
-- institutional mark, so the guía and a subject teacher have to be able to
-- reach the same row. Last write wins, and submitted_at records who was
-- last.
drop policy if exists "Teachers post conducta for their students" on public.student_conduct_grades;
create policy "Teachers post conducta for their students" on public.student_conduct_grades
  for all to authenticated
  using (student_id in (
    select s.id from public.students s
     where s.class_id in (select public.teacher_class_ids())))
  with check (student_id in (
    select s.id from public.students s
     where s.class_id in (select public.teacher_class_ids())));

drop policy if exists "Students read their conducta" on public.student_conduct_grades;
create policy "Students read their conducta" on public.student_conduct_grades
  for select
  using (student_id in (select id from public.students where auth_user_id = auth.uid()));

-- ── student_period_conduct ─────────────────────────────────────
-- The live conducta: 100 less the points deducted on this student's
-- records inside the period, floored at 0.
-- Dense on purpose — every student joined to their own year's periods, so
-- a clean record reads 100 rather than dropping out. Every student carries
-- a conducta mark from the first day of the curso lectivo, and unlike a
-- subject with no graded work, a clean discipline record IS the answer.
-- A record dated outside every period contributes to no mark; incident_count
-- is emitted so the UI can show the number the score was actually built from.
-- `security_invoker = true` is load-bearing. A view runs as its owner by
-- default, which bypasses RLS — a student who can see one row in `students`
-- could otherwise read every student's conducta through it. Requires
-- Postgres 15+; do not drop this option.
create or replace view public.student_period_conduct
with (security_invoker = true) as
with ded as (
  select
    dr.student_id,
    gp.id                                as grading_period_id,
    count(*)                             as incident_count,
    sum(greatest(dr.conduct_points, 0))  as points
  from public.discipline_records dr
  join public.grading_periods gp
    on dr.date between gp.start_date and gp.end_date
  group by dr.student_id, gp.id
)
select
  s.id                                                as student_id,
  gp.id                                               as grading_period_id,
  round(greatest(100 - coalesce(d.points, 0), 0), 2)  as conduct_score,
  round(coalesce(d.points, 0), 2)                     as deduction,
  coalesce(d.incident_count, 0)::int                  as incident_count,
  -- Last on purpose: `create or replace view` may only append a column, so a
  -- project that already has the view takes this without a drop.
  c.id                                                as class_id
from public.students s
join public.classes c on c.id = s.class_id
join public.grading_periods gp on gp.school_year_id = c.school_year_id
left join ded d
       on d.student_id = s.id
      and d.grading_period_id = gp.id;
