-- ═══════════════════════════════════════════════════════════════
--  incremental_grade_component_templates.sql
--
--  Admin-governed MEP evaluative-component templates.
--
--  Costa Rica's REAC evaluation model grades every subject by a fixed set
--  of components — cotidiano, tareas, pruebas, proyecto, asistencia — whose
--  weights must total 100 %. Until now those components lived only as
--  free-form `grade_categories` rows a teacher typed by hand, one gradebook
--  at a time: no shared definition, no governance, nothing stopping two
--  teachers of the same subject from weighting differently or off 100.
--
--  This adds a reusable, admin-owned scheme that teachers INSTANTIATE into
--  their gradebook's grade_categories rather than retype. It does NOT change
--  grade_categories / assignments / student_grades — a template is a source
--  the teacher copies from, so existing gradebooks and the
--  student_period_grades view are untouched.
--
--  WHAT THIS DOES
--    1. grade_component_templates — a named scheme, school-wide when
--       subject_id is null or scoped to one subject. `is_default` marks the
--       school's standard scheme; at most one default per scope is enforced
--       in the admin console (mirroring how a single school year is made
--       active), not by a constraint, so setting a new default never has to
--       fight a partial unique index mid-write.
--    2. grade_component_template_items — the components of a template and
--       their weights. The 100 % rule is validated in the admin UI (shared
--       with grading-period weights, src/js/gradingPeriods.js); the column
--       only guards non-negativity, exactly like grade_categories.weight.
--    3. RLS: admins manage templates; every authenticated user may read them
--       (a teacher instantiates them). Templates hold no student data.
--
--  ORDER OF APPLICATION
--    1. school_schema.sql (or an already-provisioned project)
--    2. this file
--    3. supabase/schema/rls_audit.sql              ← verify
--    On the DEMO project only, also, in this order:
--    4. supabase/schema/demo_seed_grade_components.sql   ← a default scheme
--    5. supabase/schema/demo_lockdown.sql          ← RE-RUN: new tables need
--       their demo_deny_* policies or the demo becomes writable on them.
--
--  Idempotent: `create table if not exists`, guarded policy drops.
--  See docs/ONBOARDING_RUNBOOK.md.
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.grade_component_templates (
  id integer generated by default as identity primary key,
  name character varying(100) not null,
  subject_id integer references public.subjects(id) on delete cascade,
  is_default boolean not null default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.grade_component_template_items (
  id integer generated by default as identity primary key,
  template_id integer not null
    references public.grade_component_templates(id) on delete cascade,
  name character varying(100) not null,
  weight numeric(5,2) not null default 0 check (weight >= 0),
  item_order integer not null default 0,
  unique (template_id, name)
);

create index if not exists idx_gcti_template_id
  on public.grade_component_template_items(template_id);

-- ── RLS (these tables are not in school_schema.sql's admin-policy loop) ──
alter table public.grade_component_templates enable row level security;
alter table public.grade_component_template_items enable row level security;

drop policy if exists "Admins have full access to grade_component_templates"
  on public.grade_component_templates;
create policy "Admins have full access to grade_component_templates"
  on public.grade_component_templates for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated can read grade_component_templates"
  on public.grade_component_templates;
create policy "Authenticated can read grade_component_templates"
  on public.grade_component_templates for select
  using (auth.role() = 'authenticated');

drop policy if exists "Admins have full access to grade_component_template_items"
  on public.grade_component_template_items;
create policy "Admins have full access to grade_component_template_items"
  on public.grade_component_template_items for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated can read grade_component_template_items"
  on public.grade_component_template_items;
create policy "Authenticated can read grade_component_template_items"
  on public.grade_component_template_items for select
  using (auth.role() = 'authenticated');
