-- ═══════════════════════════════════════════════════════════════
--  school_schema.sql — baseline schema for a real (per-school) SMP project
--
--  Apply this to a fresh, empty Supabase project to onboard a school.
--  It mirrors the shared demo project's schema EXCEPT it omits the
--  demo read-only "demo_deny_*" restrictive policies — so admins can
--  actually write. Row-level security still applies: every table has an
--  is_admin() full-access policy plus the same student/teacher read
--  policies as the demo. Id columns use identity (functionally identical
--  to the demo's sequences).
--
--  Idempotent-ish: safe to run once on an empty project. See
--  docs/ONBOARDING_RUNBOOK.md for the full onboarding steps.
-- ═══════════════════════════════════════════════════════════════

-- ── Role enum ───────────────────────────────────────────────────
do $$ begin
  create type public.user_role_enum as enum ('student', 'teacher', 'admin');
exception when duplicate_object then null; end $$;

-- ═══════════════════════════════════════════════════════════════
--  Tables (created before the functions/policies that reference them)
-- ═══════════════════════════════════════════════════════════════
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role public.user_role_enum default 'student'::public.user_role_enum,
  created_at timestamp without time zone default now()
);

create table public.app_config (
  key text primary key,
  value text not null
);

-- Single-row school identity + per-school terminology (what the national-ID
-- field is called here — "Cédula", "DIMEX", a school-issued "Carné").
-- Not a general custom-fields system; `check (id = 1)`
-- keeps it compatible with the console's id-keyed table gateway.
create table public.school_settings (
  id integer primary key default 1 check (id = 1),
  name text,
  logo_url text,
  id_label text,
  created_at timestamp with time zone default now()
);
insert into public.school_settings (id) values (1) on conflict (id) do nothing;

create table public.school_years (
  id integer generated by default as identity primary key,
  name character varying(20) not null unique,
  start_date date not null,
  end_date date not null,
  is_active boolean default false,
  created_at timestamp with time zone default now()
);

create table public.grade_levels (
  id integer generated by default as identity primary key,
  name character varying(50) not null unique,
  numeric_level integer not null unique
);

create table public.rooms (
  id integer generated by default as identity primary key,
  name character varying(50) not null unique,
  capacity integer,
  type character varying(30) default 'classroom'::character varying
    check (type::text = any (array['classroom','lab','gym','library','auditorium','office']::text[]))
);

create table public.subjects (
  id integer generated by default as identity primary key,
  name character varying(100) not null unique,
  code character varying(10) unique,
  description text,
  color character varying(7)
);

create table public.teachers (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  email character varying(150) unique,
  phone character varying(20),
  address text,
  hire_date date,
  specialization character varying(100),
  status character varying(20) default 'active'::character varying
    check (status::text = any (array['active','inactive','on_leave']::text[])),
  created_at timestamp with time zone default now(),
  auth_user_id uuid unique references auth.users(id) on delete set null
);

create table public.staff (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  role character varying(50) not null,
  email character varying(150) unique,
  phone character varying(20),
  hire_date date,
  status character varying(20) default 'active'::character varying
    check (status::text = any (array['active','inactive']::text[])),
  created_at timestamp with time zone default now()
);

create table public.guardians (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  relationship character varying(50),
  phone character varying(20),
  alt_phone character varying(20),
  email character varying(150),
  address text,
  occupation character varying(100),
  created_at timestamp with time zone default now()
);

create table public.classes (
  id integer generated by default as identity primary key,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  grade_level_id integer not null references public.grade_levels(id),
  section character varying(10) not null,
  display_name character varying(20),
  homeroom_teacher_id integer references public.teachers(id) on delete set null,
  room_id integer references public.rooms(id) on delete set null,
  max_capacity integer default 30,
  unique (school_year_id, grade_level_id, section)
);

create table public.students (
  id integer generated by default as identity primary key,
  first_name character varying(100) not null,
  last_name character varying(100) not null,
  national_id character varying(20) unique,
  enrollment_number character varying(20) not null unique,
  date_of_birth date,
  gender character(1) check (gender = any (array['M'::bpchar,'F'::bpchar,'O'::bpchar])),
  class_id integer references public.classes(id) on delete set null,
  phone character varying(20),
  email character varying(150),
  address text,
  photo_url text,
  status character varying(20) default 'active'::character varying
    check (status::text = any (array['active','inactive','graduated','transferred','withdrawn']::text[])),
  enrollment_date date default CURRENT_DATE,
  created_at timestamp with time zone default now(),
  auth_user_id uuid references auth.users(id)
);

create table public.student_guardians (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  guardian_id integer not null references public.guardians(id) on delete cascade,
  is_primary boolean default false,
  unique (student_id, guardian_id)
);

create table public.grade_level_subjects (
  id integer generated by default as identity primary key,
  grade_level_id integer not null references public.grade_levels(id) on delete cascade,
  subject_id integer not null references public.subjects(id) on delete cascade,
  weekly_hours integer default 4,
  unique (grade_level_id, subject_id)
);

create table public.class_subject_teachers (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  subject_id integer not null references public.subjects(id) on delete cascade,
  teacher_id integer not null references public.teachers(id) on delete restrict,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  unique (class_id, subject_id, school_year_id)
);

create table public.grading_periods (
  id integer generated by default as identity primary key,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  name character varying(50) not null,
  start_date date not null,
  end_date date not null,
  weight numeric(5,2) default 50.00,
  period_order integer not null,
  unique (school_year_id, period_order)
);

create table public.schedules (
  id integer generated by default as identity primary key,
  class_id integer not null references public.classes(id) on delete cascade,
  subject_id integer not null references public.subjects(id) on delete cascade,
  teacher_id integer not null references public.teachers(id) on delete cascade,
  day_of_week smallint not null check (day_of_week >= 1 and day_of_week <= 7),
  start_time time without time zone not null,
  end_time time without time zone not null,
  room_id integer references public.rooms(id) on delete set null,
  unique (class_id, day_of_week, start_time)
);

-- Which structure a year's schedules use, and which days its week runs on.
-- structure_type is the hook for future structures (per-student schedules
-- would widen the CHECK); only 'section' is implemented today.
create table public.schedule_configs (
  id integer generated by default as identity primary key,
  school_year_id integer not null references public.school_years(id) on delete cascade,
  structure_type character varying(20) not null default 'section'
    check (structure_type::text = any (array['section']::text[])),
  active_days smallint[] not null default '{1,2,3,4,5}'
    check (
      active_days <@ array[1,2,3,4,5,6,7]::smallint[]
      and cardinality(active_days) > 0
    ),
  created_at timestamp with time zone default now(),
  unique (school_year_id)
);

-- Reusable time-block templates. Applying one prefills the schedule
-- editor; entries still store their own times, so nothing here is
-- referenced by public.schedules.
create table public.bell_schedules (
  id integer generated by default as identity primary key,
  name character varying(80) not null unique,
  created_at timestamp with time zone default now()
);

create table public.bell_schedule_blocks (
  id integer generated by default as identity primary key,
  bell_schedule_id integer not null references public.bell_schedules(id) on delete cascade,
  label character varying(80) not null,
  kind character varying(20) not null default 'class'
    check (kind::text = any (array['class','break']::text[])),
  block_order integer not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  check (start_time < end_time),
  unique (bell_schedule_id, block_order)
);

create table public.attendance (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  class_id integer not null references public.classes(id) on delete cascade,
  -- Nullable: which subject this record belongs to. Lets two teachers
  -- sharing a section each keep their own attendance for the same day
  -- instead of overwriting one another. See
  -- incremental_attendance_by_subject.sql for the backfill this shape
  -- required on projects that predate it.
  class_subject_teacher_id integer references public.class_subject_teachers(id) on delete set null,
  date date not null,
  status character varying(20) not null
    check (status::text = any (array['present','absent','late','excused']::text[])),
  notes text,
  recorded_by integer references public.teachers(id) on delete set null,
  created_at timestamp with time zone default now(),
  unique (student_id, class_subject_teacher_id, date)
);

create index idx_attendance_class_subject_teacher_id on public.attendance(class_subject_teacher_id);

create table public.grade_categories (
  id integer generated by default as identity primary key,
  class_subject_teacher_id integer not null references public.class_subject_teachers(id) on delete cascade,
  name character varying not null,
  weight numeric not null default 0 check (weight >= 0),
  created_at timestamp with time zone default now(),
  unique (class_subject_teacher_id, name)
);

create table public.assignments (
  id integer generated by default as identity primary key,
  class_subject_teacher_id integer not null references public.class_subject_teachers(id) on delete cascade,
  grading_period_id integer not null references public.grading_periods(id) on delete restrict,
  name character varying(150) not null,
  due_date date,
  max_score numeric(6,2) not null default 100 check (max_score > 0),
  note text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  category_id integer references public.grade_categories(id) on delete set null
);

create table public.assignment_grades (
  id integer generated by default as identity primary key,
  assignment_id integer not null references public.assignments(id) on delete cascade,
  student_id integer not null references public.students(id) on delete cascade,
  score numeric(6,2) check (score >= 0),
  note text,
  graded_at timestamp with time zone default now(),
  created_at timestamp with time zone not null default now(),
  unique (assignment_id, student_id)
);

create table public.student_grades (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  class_subject_teacher_id integer not null references public.class_subject_teachers(id) on delete cascade,
  grading_period_id integer not null references public.grading_periods(id) on delete cascade,
  score numeric(5,2) check (score >= 0 and score <= 100),
  notes text,
  submitted_at timestamp with time zone default now(),
  unique (student_id, class_subject_teacher_id, grading_period_id)
);

-- Admin-governed MEP evaluative-component schemes. A template is school-wide
-- (subject_id null) or scoped to a subject; teachers instantiate its items into
-- their gradebook's grade_categories. See
-- supabase/schema/incremental_grade_component_templates.sql.
create table public.grade_component_templates (
  id integer generated by default as identity primary key,
  name character varying(100) not null,
  subject_id integer references public.subjects(id) on delete cascade,
  is_default boolean not null default false,
  created_at timestamp with time zone default now()
);

create table public.grade_component_template_items (
  id integer generated by default as identity primary key,
  template_id integer not null references public.grade_component_templates(id) on delete cascade,
  name character varying(100) not null,
  weight numeric(5,2) not null default 0 check (weight >= 0),
  item_order integer not null default 0,
  unique (template_id, name)
);

create index idx_gcti_template_id on public.grade_component_template_items(template_id);

create table public.discipline_records (
  id integer generated by default as identity primary key,
  student_id integer not null references public.students(id) on delete cascade,
  date date not null default CURRENT_DATE,
  type character varying(50) not null,
  description text,
  severity character varying(20) default 'low'::character varying
    check (severity::text = any (array['low','medium','high']::text[])),
  reported_by_teacher integer references public.teachers(id) on delete set null,
  reported_by_staff integer references public.staff(id) on delete set null,
  resolved boolean default false,
  resolution text,
  created_at timestamp with time zone default now()
);

create table public.events (
  id integer generated by default as identity primary key,
  title character varying(200) not null,
  description text,
  start_date date not null,
  end_date date,
  type character varying(30) default 'general'::character varying
    check (type::text = any (array['holiday','exam_period','activity','parent_meeting','suspension','general']::text[])),
  affects_classes boolean default true,
  created_by integer references public.staff(id) on delete set null,
  created_at timestamp with time zone default now()
);

-- ═══════════════════════════════════════════════════════════════
--  Functions + auth→profiles trigger (after the tables they touch)
-- ═══════════════════════════════════════════════════════════════
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path to 'public'
as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path to 'public'
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Harden the SECURITY DEFINER helpers: handle_new_user() only runs from the
-- trigger; is_admin() is evaluated by authenticated users inside RLS policies
-- (so it keeps EXECUTE for authenticated) but anon never needs it.
revoke execute on function public.handle_new_user() from anon, authenticated, public;
revoke execute on function public.is_admin() from anon;

-- ── Grading periods stay inside their school year ───────────────
-- The bounds live in another table, so this can't be a CHECK constraint. The
-- admin console enforces the same two rules inline (src/js/validate.js);
-- the trigger backstops CSV import, the SQL editor and any future API client.
-- Mirrored as an apply-by-hand snippet in
-- supabase/schema/incremental_grading_period_bounds.sql.
create or replace function public.grading_period_within_year()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  y_start date;
  y_end   date;
begin
  if new.start_date > new.end_date then
    raise exception
      'Grading period start date (%) must be on or before its end date (%)',
      new.start_date, new.end_date
      using errcode = 'check_violation';
  end if;

  select start_date, end_date into y_start, y_end
  from public.school_years
  where id = new.school_year_id;

  if y_start is null then
    raise exception 'School year % not found', new.school_year_id
      using errcode = 'foreign_key_violation';
  end if;

  if new.start_date < y_start or new.end_date > y_end then
    raise exception
      'Grading period % to % falls outside its school year % (% to %)',
      new.start_date, new.end_date, new.school_year_id, y_start, y_end
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

revoke execute on function public.grading_period_within_year()
  from anon, authenticated, public;

drop trigger if exists grading_periods_within_year on public.grading_periods;
create trigger grading_periods_within_year
  before insert or update on public.grading_periods
  for each row execute function public.grading_period_within_year();

-- ═══════════════════════════════════════════════════════════════
--  Row-level security: admin full access + student/teacher reads
--  (no demo read-only lock — admins can write on a real project)
-- ═══════════════════════════════════════════════════════════════
do $$
declare tbl text;
begin
  foreach tbl in array array[
    'profiles','app_config','school_settings','school_years','grade_levels','rooms','subjects',
    'teachers','staff','guardians','classes','students','student_guardians',
    'grade_level_subjects','class_subject_teachers','grading_periods','schedules',
    'schedule_configs','bell_schedules','bell_schedule_blocks',
    'attendance','grade_categories','assignments','assignment_grades',
    'student_grades','discipline_records','events',
    'grade_component_templates','grade_component_template_items'
  ]
  loop
    execute format('alter table public.%I enable row level security;', tbl);
  end loop;

  -- Admins can do everything on every table.
  foreach tbl in array array[
    'profiles','app_config','school_settings','school_years','grade_levels','rooms','subjects',
    'teachers','staff','guardians','classes','students','student_guardians',
    'grade_level_subjects','class_subject_teachers','grading_periods','schedules',
    'schedule_configs','bell_schedules','bell_schedule_blocks',
    'attendance','grade_categories','assignments','assignment_grades',
    'student_grades','discipline_records','events',
    'grade_component_templates','grade_component_template_items'
  ]
  loop
    execute format(
      'create policy "Admins have full access to %1$s" on public.%1$I '
      || 'for all to authenticated using (public.is_admin()) with check (public.is_admin());',
      tbl);
  end loop;

  -- Authenticated users can read reference/structure tables.
  -- `teachers` is deliberately absent: RLS filters rows, not columns, so a
  -- blanket read here would hand every signed-in user each teacher's
  -- national_id, phone, address and hire_date. It gets admin + self-read
  -- plus the PII-free `teachers_directory` view at the end of this file.
  -- `schedules` is here so teaching staff can read the timetable of the
  -- classes they teach; the narrower student policy further down stays
  -- (policies are OR'd) and documents the student's own-class read.
  foreach tbl in array array[
    'app_config','school_settings','school_years','grade_levels','rooms','subjects',
    'classes','grade_level_subjects','class_subject_teachers','grading_periods','events',
    'schedules','schedule_configs','bell_schedules','bell_schedule_blocks',
    'grade_component_templates','grade_component_template_items'
  ]
  loop
    execute format(
      'create policy "Authenticated can read %1$s" on public.%1$I '
      || 'for select using (auth.role() = ''authenticated'');',
      tbl);
  end loop;
end $$;

-- Own-profile read/update.
-- The update policy lets a user maintain their own display name. RLS picks
-- rows, not columns, so on its own it would also let them rewrite their own
-- `role` and land as an admin — see the trigger right below, which is what
-- actually holds that line. Do not drop one without the other.
create policy "Users can read their own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- Role changes are an admin action, enforced where RLS cannot reach: a
-- column. Without this a signed-in student could PATCH their own profile
-- row to role='admin' using the anon key that ships in the browser bundle,
-- and is_admin() would then hand them every record in the school.
-- SECURITY INVOKER (the default) is deliberate — the guard needs the role
-- the caller actually connected as, which a definer function would hide.
create or replace function public.protect_profile_role()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  if new.role is not distinct from old.role then
    return new;
  end if;

  -- anon and authenticated are the untrusted, browser-facing roles. Anything
  -- else (service_role for the admin-users Edge Function, postgres for the
  -- dashboard) already holds the service key and is trusted to assign roles.
  if current_user = 'anon' then
    raise exception 'Only an administrator can change a profile role'
      using errcode = '42501';
  end if;

  if current_user = 'authenticated' and not public.is_admin() then
    raise exception 'Only an administrator can change a profile role'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke execute on function public.protect_profile_role() from anon, authenticated, public;

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role
  before update on public.profiles
  for each row execute function public.protect_profile_role();

-- Students read their own linked rows.
create policy "Users can read their own student record" on public.students
  for select using (auth.uid() = auth_user_id);
create policy "Students read their attendance" on public.attendance
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their grades" on public.student_grades
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their discipline" on public.discipline_records
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their guardian links" on public.student_guardians
  for select using (student_id in (select id from public.students where auth_user_id = auth.uid()));
create policy "Students read their guardians" on public.guardians
  for select using (id in (
    select sg.guardian_id from public.student_guardians sg
    join public.students s on s.id = sg.student_id
    where s.auth_user_id = auth.uid()));
create policy "Students read their class schedule" on public.schedules
  for select using (class_id in (select class_id from public.students where auth_user_id = auth.uid()));

-- Teachers read their own full record.
-- The read-only Settings view in the teacher console needs national_id, phone,
-- address and hire_date for the logged-in teacher, and only them. Requires
-- teachers.auth_user_id to be populated for every teacher who signs in.
create policy "Teachers can read their own full record" on public.teachers
  for select to authenticated
  using (auth_user_id = auth.uid());

-- PII-free teacher directory.
-- Every legitimate cross-user name lookup reads this instead of the base
-- table: the student portal's teacher list, homeroom-teacher name, the
-- discipline/attendance recorder name, and the teacher console's colleague
-- lookups. Deliberately NOT security_invoker — it must return every teacher
-- row regardless of caller, which the narrowed base-table policy above would
-- not allow. Safe because the column list structurally excludes the PII.
drop view if exists public.teachers_directory;
create view public.teachers_directory as
  select id, first_name, last_name, specialization, email, status
  from public.teachers;

revoke all on public.teachers_directory from anon, public;
grant select on public.teachers_directory to authenticated;

-- ═══════════════════════════════════════════════════════════════
--  Teacher-scoped RLS + the gradebook's computed-score view.
--  Kept in sync with supabase/schema/incremental_teacher_policies.sql,
--  which applies the same objects to an already-provisioned project.
--  Without these a `teacher` account cannot read a single student and the
--  teacher console is dead, so a fresh project needs them from the start.
--  Every policy here is rooted in teacher_id(), which resolves through
--  teachers.auth_user_id — populate that column for each teacher who signs
--  in, or all of them match nothing.
-- ═══════════════════════════════════════════════════════════════

-- ── Helpers ────────────────────────────────────────────────────
-- SECURITY DEFINER because a policy on `teachers` would otherwise have to
-- read `teachers` to decide whether you may read `teachers`. Fixed
-- search_path per the same hardening as is_admin() / handle_new_user().
-- EXECUTE stays granted to `authenticated` (policies evaluate as the
-- calling role); `anon` and `public` have no business calling these.

create or replace function public.teacher_id()
returns integer
language sql
stable
security definer
set search_path to 'public'
as $$
  select id from public.teachers where auth_user_id = auth.uid();
$$;

revoke execute on function public.teacher_id() from anon, public;

-- Every class the caller teaches: subject assignments plus homeroom.
create or replace function public.teacher_class_ids()
returns setof integer
language sql
stable
security definer
set search_path to 'public'
as $$
  select cst.class_id
    from public.class_subject_teachers cst
   where cst.teacher_id = public.teacher_id()
  union
  select c.id
    from public.classes c
   where c.homeroom_teacher_id = public.teacher_id();
$$;

revoke execute on function public.teacher_class_ids() from anon, public;

-- Every class_subject_teachers row the caller owns. The gradebook tables
-- hang off this id, so most policies below are one lookup against it.
create or replace function public.teacher_cst_ids()
returns setof integer
language sql
stable
security definer
set search_path to 'public'
as $$
  select id from public.class_subject_teachers where teacher_id = public.teacher_id();
$$;

revoke execute on function public.teacher_cst_ids() from anon, public;

-- ── Students ───────────────────────────────────────────────────
-- Read-only: rosters are an admin surface. A teacher sees a student only
-- while that student sits in one of their classes.
drop policy if exists "Teachers read students in their classes" on public.students;
create policy "Teachers read students in their classes" on public.students
  for select to authenticated
  using (class_id in (select public.teacher_class_ids()));

-- ── Attendance ─────────────────────────────────────────────────
-- Full write access, scoped by class. `with check` mirrors `using` so a
-- teacher cannot move a record into a class they don't teach.
drop policy if exists "Teachers manage attendance for their classes" on public.attendance;
create policy "Teachers manage attendance for their classes" on public.attendance
  for all to authenticated
  using (class_id in (select public.teacher_class_ids()))
  with check (class_id in (select public.teacher_class_ids()));

-- ── Gradebook ──────────────────────────────────────────────────
drop policy if exists "Teachers manage their grade categories" on public.grade_categories;
create policy "Teachers manage their grade categories" on public.grade_categories
  for all to authenticated
  using (class_subject_teacher_id in (select public.teacher_cst_ids()))
  with check (class_subject_teacher_id in (select public.teacher_cst_ids()));

drop policy if exists "Teachers manage their assignments" on public.assignments;
create policy "Teachers manage their assignments" on public.assignments
  for all to authenticated
  using (class_subject_teacher_id in (select public.teacher_cst_ids()))
  with check (class_subject_teacher_id in (select public.teacher_cst_ids()));

-- Grades reach their owner through the assignment.
drop policy if exists "Teachers manage grades on their assignments" on public.assignment_grades;
create policy "Teachers manage grades on their assignments" on public.assignment_grades
  for all to authenticated
  using (assignment_id in (
    select a.id from public.assignments a
     where a.class_subject_teacher_id in (select public.teacher_cst_ids())))
  with check (assignment_id in (
    select a.id from public.assignments a
     where a.class_subject_teacher_id in (select public.teacher_cst_ids())));

drop policy if exists "Teachers manage period grades for their subjects" on public.student_grades;
create policy "Teachers manage period grades for their subjects" on public.student_grades
  for all to authenticated
  using (class_subject_teacher_id in (select public.teacher_cst_ids()))
  with check (class_subject_teacher_id in (select public.teacher_cst_ids()));

-- ── Discipline ─────────────────────────────────────────────────
-- Read anything about their own students; write only in their own name, so
-- one teacher cannot file or rewrite a report attributed to another.
drop policy if exists "Teachers read discipline for their students" on public.discipline_records;
create policy "Teachers read discipline for their students" on public.discipline_records
  for select to authenticated
  using (student_id in (
    select s.id from public.students s
     where s.class_id in (select public.teacher_class_ids())));

drop policy if exists "Teachers file their own discipline reports" on public.discipline_records;
create policy "Teachers file their own discipline reports" on public.discipline_records
  for insert to authenticated
  with check (
    reported_by_teacher = public.teacher_id()
    and student_id in (
      select s.id from public.students s
       where s.class_id in (select public.teacher_class_ids())));

drop policy if exists "Teachers update their own discipline reports" on public.discipline_records;
create policy "Teachers update their own discipline reports" on public.discipline_records
  for update to authenticated
  using (reported_by_teacher = public.teacher_id())
  with check (reported_by_teacher = public.teacher_id());

-- ── student_period_grades ──────────────────────────────────────
-- The gradebook's computed overall score: weighted by grade category where
-- categories exist, renormalised over the categories that actually have
-- graded work, falling back to raw points otherwise.
-- `security_invoker = true` is load-bearing. A view runs as its owner by
-- default, which bypasses RLS — a student who can see one row in `students`
-- could otherwise read every student's grades through it. Requires
-- Postgres 15+; do not drop this option.
create or replace view public.student_period_grades
with (security_invoker = true) as
with base as (
  select
    ag.student_id,
    a.class_subject_teacher_id,
    a.grading_period_id,
    sum(ag.score)   as sum_score,
    sum(a.max_score) as sum_max,
    count(ag.score) as graded_count,
    count(a.id)     as total_assignments
  from public.assignments a
  left join public.assignment_grades ag
         on ag.assignment_id = a.id and ag.score is not null
  group by ag.student_id, a.class_subject_teacher_id, a.grading_period_id
),
-- Only categorised work takes part in the weighted score; the join is inner
-- on purpose. Uncategorised assignments fall through to the points fallback
-- in the final select.
cat as (
  select
    ag.student_id,
    a.class_subject_teacher_id,
    a.grading_period_id,
    gc.weight as cat_weight,
    sum(ag.score) / nullif(sum(a.max_score), 0::numeric) * 100::numeric as cat_pct
  from public.assignments a
  join public.grade_categories gc on gc.id = a.category_id
  join public.assignment_grades ag
       on ag.assignment_id = a.id and ag.score is not null
  group by ag.student_id, a.class_subject_teacher_id, a.grading_period_id,
           a.category_id, gc.weight
),
-- Renormalised over the categories that actually have graded work, so a
-- period with only one category marked still reads out of 100.
weighted as (
  select
    student_id,
    class_subject_teacher_id,
    grading_period_id,
    sum(cat_pct * cat_weight) / nullif(sum(cat_weight), 0::numeric) as w_score
  from cat
  group by student_id, class_subject_teacher_id, grading_period_id
)
select
  b.student_id,
  b.class_subject_teacher_id,
  b.grading_period_id,
  round(
    coalesce(
      w.w_score,
      b.sum_score / nullif(b.sum_max, 0::numeric) * 100::numeric
    ), 2) as period_score,
  b.graded_count,
  b.total_assignments
from base b
left join weighted w
       on w.student_id = b.student_id
      and w.class_subject_teacher_id = b.class_subject_teacher_id
      and w.grading_period_id = b.grading_period_id;
